name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
   Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: setup git config
        run: |
          git config user.name "shreyaarmarkar"
          git config user.email "<>"
      
      - name: Dependecies
        run: npm ci
      
      - name: Build
        run: npm run build
        
      - name: Save version
        id: version
        run: echo "{tag}={$(echo $(node -p -e "require('./package.json').version"))}" >> $GITHUB_OUTPUT
  
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag shreyaarm/test:${{steps.version.outputs.tag}}
        
      - name: Push to Docker Hub
        run: docker push shreyaarm/test:${{steps.version.outputs.tag}}
